[NL-29] 강공격 추가 및 점프 공격 추가
Project-NL/ProjectNL pull request #24
Opened 2024-11-13 19:06 UTC by changgeunjoe

# 개요
> GA_ComboAttack에 강공격 및 점프 공격 추가 

# 작업 내용
본인이 작업한 부분에 대해 조금 더 적어주시면 좋습니다.
- 어택 시점을 Activeability가 아닌 InputReleased로 변경
- 강공격은 차지량을 기준으로 공격할 수 있도록 구현
- 점프 공격은 일정 점프량 이상이 되어야 공격가능

# 티켓 링크
https://project-nl.atlassian.net/browse/NL-29

# 변경 카테고리

- [ ] 버그 수정
- [x] 새로운 feature
- [ ] 문서 추가, 변경
- [x] 리팩토링

2024-11-14 04:05 UTC, goldfrosch requested changes

2024-11-14 04:05 UTC, goldfrosch commented on Source/ProjectNL/Character/BaseCharacter.cpp
> +void ABaseCharacter::Tick(float DeltaSeconds)
특정 액터(캐릭터)가 떨어지는가, 안떨어지는가에 대해 Tick을 이용해서 태그를 설정한다 까지는 이해했는데, 굳이 Tick으로 매번 계산해야하나 싶습니다. 이미 IsFalling()이라는 메소드가 있으니까요. 차라리 그것을 이용하는 것은 어떨까요?

매번 Tick으로 계산하는 것은 괜한 부담일 것 같습니다. 이 작업은 뭔가 개발을 위해 성능을 포기하는 것 같네요...

ex. isFalling값을 observe 해서 tag 부여하기 or 그냥 isFalling을 활용하기

2024-11-14 04:05 UTC, goldfrosch commented on Source/ProjectNL/Component/EquipComponent/EquipComponent.h
> +		, meta = (AllowPrivateAccess = true))
이거 어떻게 애니메이션 집어넣으셨나요? header만 바꾸면서 들어가는 것이 아닐텐데 혹시 BP에서 직접 주입하셨나요?
만약 그러셨다면 cpp 코드보고 수정하셔야합니다..!

2024-11-14 04:05 UTC, goldfrosch commented on Source/ProjectNL/GAS/Ability/Active/Default/ComboAttack/GA_ComboAttack.h
> +	TObjectPtr<ABaseCharacter> CurrentCharacter;
굳이 AvatorActor를 가져다 사용할 수 있는데 별도의 공간을 추가로 사용할 필요는 없어보이는데, 메모리 주소를 넣는 공간 복잡도랑 매번 cast를 할때의 시간 복잡도 비용이랑 어떤 것이 더 무거우려나요...?

2024-11-14 04:05 UTC, goldfrosch commented on Source/ProjectNL/GAS/Ability/Active/Default/ComboAttack/GA_ComboAttack.cpp
> +//#include "AT_HeavyAttack.h"
주석은 지워주십쇼

2024-11-14 04:05 UTC, goldfrosch commented on Source/ProjectNL/GAS/Ability/Active/Default/ComboAttack/GA_ComboAttack.cpp
> +//#include "AT_HeavyAttack.h"
불필요한 주석은 지워두는 게 좋을 것 같네요

2024-11-14 04:05 UTC, goldfrosch commented on Source/ProjectNL/GAS/Ability/Active/Default/ComboAttack/GA_ComboAttack.cpp
> +			GetAvatarActorFromActorInfo());
header에도 적어뒀었지만 이게 효율적인 행위인지는 잘 모르겠네요... 비교 분석할 필요가 있어보입니다.

2024-11-14 04:05 UTC, goldfrosch commented on Source/ProjectNL/GAS/Ability/Active/Default/ComboAttack/GA_ComboAttack.cpp
> +		PlayerController->SetIgnoreMoveInput(false);
이건 어떤역할인가요? Movement가 동작하지 않도록 처리하는 것 일까요?

2024-11-14 04:05 UTC, goldfrosch commented on Source/ProjectNL/GAS/Ability/Active/Default/ComboAttack/GA_ComboAttack.cpp
> +}
이건 오로지 Press가 되었다는 테스트만을 위한 함수 선언일까요? 만약 그런것이라면 지울 필요가 있어보입니다.

2024-11-14 04:05 UTC, goldfrosch commented on Source/ProjectNL/GAS/Ability/Active/Default/ComboAttack/GA_ComboAttack.cpp
> +	}
```suggestion
UAbilitySystemComponent* AbilitySystem = GetAbilitySystemComponentFromActorInfo();
check(AbilitySystem)
```
전에 if문으로 내부에 변수 선언하는 것은 별로라하셨으니 이 방식은 어떤가요? 이거랑 동일한 기능을 하니 이 방식도 괜찮아보이는데

2024-11-14 04:05 UTC, goldfrosch commented on Source/ProjectNL/GAS/Ability/Active/Default/ComboAttack/GA_ComboAttack.cpp
> +	HeavyAttackTask->ReadyForActivation();
강공격은 별도의 Notify가 필요없으셨나요? 아니면 로직이 내장되어있어서 처리 안해도 됬던 걸까요?

2024-11-14 04:05 UTC, goldfrosch commented on Source/ProjectNL/GAS/Ability/Active/Default/ComboAttack/GA_ComboAttack.cpp
> +    const FVector TraceEnd = CharacterLocation - FVector(0, 0, 1000.0f); // 레이 길이 (1000 유닛)
1000이 생각보다 짧나보군요...?
나중에는 액터의 Capsule Component의 길이를 가져와서 해봐도 좋을 것 같네요. 기회되면 연구해봐야겠군요 휴휴...

2024-11-14 12:24 UTC, changgeunjoe commented on Source/ProjectNL/Character/BaseCharacter.cpp
> +void ABaseCharacter::Tick(float DeltaSeconds)
괜찮네요 이거는 아래방법으로 변경하겠습니다.

2024-11-14 12:26 UTC, changgeunjoe commented on Source/ProjectNL/GAS/Ability/Active/Default/ComboAttack/GA_ComboAttack.h
> +	TObjectPtr<ABaseCharacter> CurrentCharacter;
음 두 방법 다 문제 없을 거라고 생각합니다.

2024-11-14 12:27 UTC, changgeunjoe commented on Source/ProjectNL/GAS/Ability/Active/Default/ComboAttack/GA_ComboAttack.cpp
> +//#include "AT_HeavyAttack.h"
넵!

2024-11-14 14:24 UTC, changgeunjoe commented on Source/ProjectNL/GAS/Ability/Active/Default/ComboAttack/GA_ComboAttack.cpp
> +//#include "AT_HeavyAttack.h"
넵 수정하겠습니다

2024-11-14 14:24 UTC, changgeunjoe commented on Source/ProjectNL/GAS/Ability/Active/Default/ComboAttack/GA_ComboAttack.cpp
> +		PlayerController->SetIgnoreMoveInput(false);
점프시 무브먼트 입력이 작동하지 않도록 한 것입니다.

2024-11-14 14:24 UTC, changgeunjoe commented on Source/ProjectNL/GAS/Ability/Active/Default/ComboAttack/GA_ComboAttack.cpp
> +}
테스트만을 위한 함수입니다.

2024-11-14 14:25 UTC, changgeunjoe commented on Source/ProjectNL/GAS/Ability/Active/Default/ComboAttack/GA_ComboAttack.cpp
> +	HeavyAttackTask->ReadyForActivation();
강공격은 별도의 Notify가 필요 없습니다

2024-11-14 14:26 UTC, changgeunjoe commented on Source/ProjectNL/Component/EquipComponent/EquipComponent.h
> +		, meta = (AllowPrivateAccess = true))
BP작업으로 했습니다

2024-11-14 14:34 UTC, changgeunjoe commented on Source/ProjectNL/Component/EquipComponent/EquipComponent.h
> +		, meta = (AllowPrivateAccess = true))
이거 코드를 넣는 식으로 하면 SetAnimationsByWeaponState가 너무 길어지고 복잡해질 거 같은데 어떻게 생각하시나요?

2024-11-14 14:44 UTC, goldfrosch commented on Source/ProjectNL/Component/EquipComponent/EquipComponent.h
> +		, meta = (AllowPrivateAccess = true))
저도 그 부분에 대해서는 동의합니다만 당장 떠오르는 로직은 없습니다. ㅠㅠ... 대안이 있을까요?

2024-11-15 05:31 UTC, changgeunjoe commented on Source/ProjectNL/Component/EquipComponent/EquipComponent.h
> +		, meta = (AllowPrivateAccess = true))
음 데이터 테이블을 변경해야 한다고 생각을 해요

2024-11-15 05:36 UTC, changgeunjoe commented on Source/ProjectNL/Component/EquipComponent/EquipComponent.h
> +		, meta = (AllowPrivateAccess = true))
현재는 애니메이션의 환경에 따라 데이터 테이블을 분리해서 줄이 많아 질 수 밖에 없는데 이거를 ->무기 종류별로 애니메이션 묶음을 만들어주고 캐릭터의 무기 종류에 맞게 애니메이션을 불러오는게 맞다고 생각을 합니다.
![제목 없음](https://github.com/user-attachments/assets/cda600b7-09b7-43f2-ac04-1002e883ca93)
 이렇게 되면은 무기를 교환할 때 무기에 맞는 애니메이션을 한번에 불러올 수 있는 이점도 생길 거라고 생각합니다.

2024-11-15 11:55 UTC, changgeunjoe commented on Source/ProjectNL/GAS/Ability/Active/Default/ComboAttack/GA_ComboAttack.cpp
> +	}
수정했습니다

2024-11-19 06:59 UTC, merged